사용자 회원 등록 및 수정 API 기능 및 테스트 코드 작성
f-lab-edu/EV-charging-platform pull request #10
Opened 2022-09-18 14:30 UTC by shinsanghooon

다음 이슈에 대한 PR입니다. 
- #8
- #9

2022-09-18 15:13 UTC, kyucumber requested changes

2022-09-18 15:13 UTC, kyucumber commented on build.gradle
> +    implementation("org.springframework.boot:spring-boot-starter-validation")
안그래도 요거 말씀드리려고 했는데 이미 적용하셨네요 👍

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/api/UserController.java
> +@RequestMapping("/users")
API가 변하는 부분(버저닝)과 외부 API, 내부 API 구분을 위해 아래와 같이 사용하는 경우도 있습니다. 참고 부탁드려요.

```suggestion
@RequestMapping("/api/v1/users")
```

내부는 `webapi`, 외부는 `api` 요런식으로 분리해서 사용할수도 있어요.
그리고 인증이 적용될 경로와 적용되지 않을 경로(헬스체크 등)을 구분할 필요가 있는 경우가 있어서 앞에 위와 같이 접두사가 붙는게 좋을 것 같아요.

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/api/UserController.java
> +     */
개인적으로는 java doc 관련 주석을 모든 메소드에 남길 필요는 없다고 생각합니다.

REST API를 잘 설계했다면 HTTP 메소드나 자원 명, 메소드 명과 반환 타입을 통해 어떤 자원에 대해 다루는지 충분히 이해할 수 있다고 생각해요.

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/api/UserController.java
> +    @PostMapping("/email/check")
중복 여부라는 자원의 조회로 본다면 `@GetMapping`으로도 사용할 수 있지 않을까요?

단순 이메일의 중복 여부를 체크하는 기능이라면 보안적인 문제도 없을 것 같아 `@PostMapping`을 사용하지 않아도 괜찮을 것 같아요.

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/api/UserController.java
> +    @GetMapping("/users/{id}")
`/users/users/{id}`로 users가 중복해서 URL에 표시되는 것 같아요.

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/application/UserService.java
> +            throw new EmailDuplicateException();
모든 예외를 커스텀으로 만들 필요는 없다고 생각해요.
이미 존재하는 표준 예외에 적절한 메시지를 통해 어떤 예외 상황인지를 나타내주어도 충분하지 않을까요?

아래 내용을 한번 참고해보세요.

https://insight-bgh.tistory.com/470

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/application/UserService.java
> +        return userRepository.save(user.toEntity());
DTO의 불변이 해당 메소드 호출로 인해 깨졌고, DTO와 PasswordEncoder간의 결합이 생겼네요.

크게 중요한 부분은 아니지만 아래와 같이 정의하면 불변을 유지할 수 있지 않을까요?

```suggestion
        String encryptedPassword = ~~
        return userRepository.save(user.toEntity(encryptedPassword));
```

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/application/UserService.java
> +    }
findById 메소드 내부에서 해당 아이디로 조회하지 못하는 경우 예외를 던지고 있네요.

JPA의 repository의 findById는 어떻게 동작하는지 찾아보시고 get과 find 접두사가 붙은 메소드들에 대해 어떤 의미 차이가 있을지 한번 고민해보세요

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/application/UserService.java
> +    public boolean checkEmailDuplicate(EmailDuplicateCheckRequestDto emailDuplicateCheckRequestDto) {
check의 경우 stdlib에서도 보통 void 형태의 메소드로 정의되었던 걸로 기억합니다.

실제로 Kotlin의 check라는 stdlib 함수도 체크 후 예외를 던지지 boolean 값을 리턴하는 형태는 아니에요.

대부분 check~~와 같이 네이밍되었다면 조건을 체크 후 예외를 던지는 형태로 생각할 것 같은데요 boolean 타입의 반환을 예상할 수 있는 메소드명으로 변경하면 어떨까요?

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/domain/User.java
> +public class User{
코드 포맷팅이 제대로 되어있지 않네요.

이후에 시간이 나시면 프리커밋 훅을 통해 lint를 자동으로 돌려 포맷팅을 맞춰주거나 체크해주는 부분을 넣어보아도 좋을 것 같습니다.

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/dto/ErrorResponse.java
> +public class ErrorResponse {
Dto의 네이밍 컨벤션은 `~~Dto`로 끝나는 거 같은데 이 클래스는 컨벤션이 맞지 않네요.

중요한 부분은 아니지만 클래스의 일관성을 해치기 때문에 다른 부분의 `~~Dto`를 제거하거나 요 클래스에 Dto를 추가해주시면 좋을 것 같아요.

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/dto/UserModifyRequestDto.java
> +    @Size(max=20, message="이름의 최대 길이는 20자 입니다.")
코드 포맷팅이 제대로 안 돈 것 같아요. IDE 설정을 한번 확인 부탁드립니다.

설정이 정상적으로 되어 있다면 코드 포맷을 자주 맞춰주시면 좋을 것 같아요.

별 거 아니지만 협업을 할 때 이 모든게 file change로 잡히게 되고 코드리뷰때 불필요한 file change로 인해 중요한 부분을 놓칠 수도 있습니다.

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/exception/UserExceptionHandler.java
> +        return new ErrorResponse(errors.get(0));
현재 0번째만 가져오고 있어서 여러 필드에 동시에 오류가 난 경우는 값을 식별하기가 어려울 것 같아요.

ErrorResponse의 메시지를 리스트로 변경하거나 Collectors.joining()인가 그런게 있었던 것 같은데 에러 메시지를 이어 붙여 반환하면 어떨까요?

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/repository/UserSearchCond.java
> +public class UserSearchCond {
Cond라는 네이밍은 어떤 의미인가요?

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/repository/mybatis/UserMapper.java
> +    Long update(Long id, @Param("userModifyRequestDto") UserModifyRequestDto userModifyRequestDto);
개인적으로는 UserMapper를 포함해서 Repository 레이어까지 Dto가 침범하는건 좋지 않은 구현이라고 생각해요.

JPA로 예를 들면 Repository 레이어에서는 User Entity를 반환하겠죠.

물론 변환하거나 하는 비용이 상당하긴 하겠지만 컨트롤러 레이어에서 데이터를 주고받을 목적으로 만든 Dto가 하위 레이어까지 침범하면 Dto의 변경에 모든 레이어가 영향을 받을 것 같습니다.

변환하는 비용이 너무 크기 때문에 예시로 보여드릴때도 그렇게 짜지는 않았지만 정말 빡빡하게 규칙을 잡는다면 Service가 Dto를 반환하는것도 문제가 될 수 있긴 해요.

2022-09-18 15:13 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/utils/PasswordEncoder.java
> +public class PasswordEncoder {
직접 구현하셨네요.

이후에 시큐리티를 적용하거나 사용할 일이 있다면 아래 클래스를 사용하셔도 좋을 것 같습니다.

https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/bcrypt/BCryptPasswordEncoder.html

2022-09-18 15:13 UTC, kyucumber commented on src/main/resources/com/shyb/evcharging/user/repository/mybatis/UserMapper.xml
> +    <select id="findById" resultType="UserResponseDto">
위에 적었지만 가급적 Repository 레이어에서 Dto를 반환하는걸 지양해주셨으면 해요.

2022-09-18 15:13 UTC, kyucumber commented on src/test/java/com/shyb/evcharging/user/application/UserServiceTest.java
> +            .build();
테스트를 위해 준비해야하는 데이터들이 많고 이런 코드가 많아짐에 따라 테스트 클래스의 상당부분을 차지해 가독성이 떨어집니다.

TestFixture에 대한 내용을 검색하고 테스트를 위한 데이터를 만들기 위한 별도의 클래스를 만들어보셔도 좋을 것 같아요.

2022-09-19 03:40 UTC, shinsanghooon commented on src/test/java/com/shyb/evcharging/user/application/UserServiceTest.java
> +        @DisplayName("사용자가 있으면 사용자 정보를 수정한 후 리턴한다.")
테스트 코드 작성 질문이 있습니다. 
사용자 정보 수정을 할 때 mybatis를 사용하면 update를 실행할 때 정보가 수정된 사용자 객체를 받아 오는 방법이 없더라구요.(또는 제가 못찾은 걸 수도 있습니다...ㅎㅎ)

그래서 `userService.update()` 메소드 내부에 `userService.update()`에 사용자 정보를 업데이트 하기 전에 `findById()`를 호출해서 등록된 사용자인지 확인하는 코드와 정보 업데이트 이후에 다시 `findById()`를 사용해 업데이트 된 사용자 정보를 조회해서 리턴하는 코드를 작성하였습니다.

이런 상황에서 테스트 코드를 작성하는데 어려움을 겪었습니다. 
등록된 사용자가 존재한다는 것을 알려주기 위해 mock 객체에 대한 조건을 아래처럼 미리 작성해두었는데요. 
`given(userRepository.findById(USER_ID)).willReturn(Optional.of(userResponseDto));`
그런데 이로 인해 userService.update()가 리턴하는 값 또한 userResponseDto가 되는 상황이 발생했습니다. 따라서 사용자 정보가 잘 수정되었는지에 대한 테스트 코드를 작성하지 못하였습니다.

이것저것 찾아보기도 하고 고민도 해보았지만 어떻게 해결하면 좋을지 방법이 떠오르지 않았습니다. 이런 경우 테스트 코드를 어떻게 작성하는게 좋을지 궁금합니다.

2022-09-19 03:49 UTC, shinsanghooon commented on src/test/java/com/shyb/evcharging/user/application/UserServiceTest.java
> +
테스트 코드 작성 질문이 있습니다. 
사용자 정보 수정을 할 때 mybatis를 사용하면 update를 실행할 때 정보가 수정된 사용자 객체를 받아 오는 방법이 없더라구요.(또는 제가 못찾은 걸 수도 있습니다...ㅎㅎ)

그래서 `userService.update()` 메소드 내부에 `userService.update()`에 사용자 정보를 업데이트 하기 전에 `findById()`를 호출해서 등록된 사용자인지 확인하는 코드와 정보 업데이트 이후에 다시 `findById()`를 사용해 업데이트 된 사용자 정보를 조회해서 리턴하는 코드를 작성하였습니다.

이런 상황에서 테스트 코드를 작성하는데 어려움을 겪었습니다. 
등록된 사용자가 존재한다는 것을 알려주기 위해 mock 객체에 대한 조건을 아래처럼 미리 작성해두었는데요. 
`given(userRepository.findById(USER_ID)).willReturn(Optional.of(userResponseDto));`
그런데 이로 인해 userService.update()가 리턴하는 값 또한 userResponseDto가 되는 상황이 발생했습니다. 따라서 사용자 정보가 잘 수정되었는지에 대한 테스트 코드를 작성하지 못하였습니다.

이것저것 찾아보기도 하고 고민도 해보았지만 어떻게 해결하면 좋을지 방법이 떠오르지 않았습니다. 이런 경우 테스트 코드를 어떻게 작성하는게 좋을지 궁금합니다.

2022-09-19 13:57 UTC, shinsanghooon commented on src/main/java/com/shyb/evcharging/user/repository/UserSearchCond.java
> +public class UserSearchCond {
Condition을 의미하며 사용자 조회를 할 때 조건을 담고 있는 객체이고 UserMapper.xml에서 사용됩니다. 처음에 MyBatis 세팅할 때 예시로 사용했던건데 지금은 필요하지 않아서 다음 푸시에 정리해서 올리도록 하겠습니다.

2022-09-19 14:06 UTC, shinsanghooon commented on src/main/java/com/shyb/evcharging/user/api/UserController.java
> +     */
컨트롤러에서는 말씀해주신 것처럼 REST API를 잘 설계하면 충분히 이해가 가능한 부분이라고 생각됩니다. 적으면서도 너무 뻔한걸 적는다는 느낌도 받긴 했지만 그래도 작성해두었습니다...! ㅎㅎㅎ

2022-09-19 17:04 UTC, shinsanghooon commented on src/main/java/com/shyb/evcharging/user/api/UserController.java
> +    @PostMapping("/email/check")
조회의 관점에서 바라보니 `@GetMapping` 이 의미적으로 조금 더 알맞는 거 같습니다.

2022-09-19 17:30 UTC, shinsanghooon commented on src/main/java/com/shyb/evcharging/user/application/UserService.java
> +    public boolean checkEmailDuplicate(EmailDuplicateCheckRequestDto emailDuplicateCheckRequestDto) {
check ~~ 로 메소드 명은 유지하고 대신 예외를 던지는 형태로 수정하였습니다.

2022-09-19 17:46 UTC, shinsanghooon commented on src/main/java/com/shyb/evcharging/user/application/UserService.java
> +    }
코멘트 남겨주신 것 중에 DTO 불변에 대한 것이 있었는데, 여기서도 userModifyRequestDto의 password 필드에 암호화된 패스워드 값을 변경해주고 있습니다.

그럼 여기도 다른 리뷰에서 알려주신 방법처럼 User 객체를 만들어서 userRepository.update() 메소드에 전달해주는 좋은 방법인가요? 그렇게 하면 다른 리뷰에서도 남겨주신 DTO가 Repository를 침범하는 경우를 막을 수 있을 것 같습니다.

2022-09-20 14:38 UTC, kyucumber requested changes

2022-09-20 14:38 UTC, kyucumber commented on src/test/java/com/shyb/evcharging/user/application/UserServiceTest.java
> +
> 테스트 코드 작성 질문이 있습니다.
> 사용자 정보 수정을 할 때 mybatis를 사용하면 update를 실행할 때 정보가 수정된 사용자 객체를 받아 오는 방법이 없더라구요.(또는 > 제가 못찾은 걸 수도 있습니다...ㅎㅎ)

> 그래서 userService.update() 메소드 내부에 userService.update()에 사용자 정보를 업데이트 하기 전에 findById()를 호출해서 > 등록된 사용자인지 확인하는 코드와 정보 업데이트 이후에 다시 findById()를 사용해 업데이트 된 사용자 정보를 조회해서 리턴하는 코> 드를 작성하였습니다.

위 케이스는 저도 mybatis와 관련되어서 조금 찾아봐야 할 것 같아서 관련 내용 파악한 뒤 이후에 답변 드릴게요.

> 이런 상황에서 테스트 코드를 작성하는데 어려움을 겪었습니다.

이 케이스의 경우 findById가 여러번 호출되며 이에 따라 테스트가 어려웠다는 말씀인 것 같아요.

```java
given(userRepository.findById(USER_ID))
    .willReturn(Optional.of(userResponseDto))
    .willReturn(Optional.of(updatedUserResponseDto))
```

이런 경우 위처럼 첫번째 호출에는 userResponseDto, 두번째 호출에는 updatedUserResponseDto가 반환되도록 할 수 있었던 것 같아요.

mockito consecutive calls 과 같은 키워드로 한번 찾아보시면 관련해서 나오지 않을까 싶습니다.

2022-09-20 14:43 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/application/UserService.java
> +    }
네 Dto를 넘기는 건 지양하고 Dto의 데이터를 받아서 user.update()와 같이 User 도메인 클래스 내에 update 등의 메소드를 추가하고 userRepository의 update 메소드에서 업데이트된 User 클래스를 전달받는 형태로 구현하는게 좋을 것 같아요.

2022-09-20 14:50 UTC, kyucumber commented on src/main/java/com/shyb/evcharging/user/repository/UserSearchCond.java
> +public class UserSearchCond {
요건 좀 개인적인 의견일 수 있는데 정말로 너무 긴게 아니면 Cond같은 축약어보다는 Condition을 사용하는게 좋은 것 같아요.

보는 사람에 따라 정말 상상도 못한 의미로 해석해서 오해나 버그가 생기는 경우도 있었거든요.

2022-09-20 16:52 UTC, shinsanghooon commented on src/test/java/com/shyb/evcharging/user/application/UserServiceTest.java
> +
와우 willReturn 2번 사용하니까 해결이 되었습니다! 알려주신 키워드도 찾아보도록 하겠습니다 감사합니다! 😀

2022-09-20 17:48 UTC, shinsanghooon commented on src/main/java/com/shyb/evcharging/user/application/UserService.java
> +    }
의미상으로 한 번 생각해본 바로는  get은 원하는 값을 얻기 위한 행위이고, find는 값을 얻는 것보다 값이 있는지 확인하는게 더 주요한 목적인 것 같다는 생각이 들었습니다. 

그리고 살짝 찾아보았습니다. JPA에서 관련 메서드들은 아래와 같은 특징을 가집니다.
- `findById` 의 경우, 리턴타입으로 `Optional<T>`를 가지며 값이 없는 경우 `Optional.empty()`를 리턴하게 됩니다. 즉 값이 없어도 예외가 던져지지 않습니다. (예외는 id값에 null을 넣거나 하는 경우 발생) 
- `getOne` 의 경우, 리턴타입은 그냥 T 입니다. 때문에 값이 없을 때는 예외가 던져지게 됩니다. 
- 추가로 getOne 메소드의 경우, 내부적으로 lazy loading 를 지원하고 findById의 경우에는 바로 실제 엔티티 객체를 조회한다는 차이점이 존재합니다. 

그 외에도 데이터를 가져오는 시간의 정도, 로직의 복잡도 같은 이유에 따라서도 get과 find를 구분해서 사용하기는 사례도 있는 것 같았습니다. 

만약 jpa 문서 내용이 find와 get을 구분해서 사용하는 관례라면 제가 작성한 코드는 find 메소드는 예외를 던지고 있으니 관례를 어겼다고 볼 수도 있겠네요..? 허허ㅎㅎ

2022-09-22 12:46 UTC, f-lab-kyucumber approved these changes

2022-09-22 12:46 UTC, f-lab-kyucumber commented
코멘트 내용 대부분 반영되어서 Approve 했습니다. 확인하고 머지하신 뒤 이어서 진행해주세요~

2022-09-22 13:18 UTC, merged